version: '3.8'
services:
  app:
    build: 
      dockerfile: ./CICD/app.Dockerfile
      context: ./
    command: uvicorn app.api:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    restart: always
    networks:
      - produtrue_network

  db:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - produtrue_network

volumes:
  pgdata:

networks:
  produtrue_network:
    driver: bridge
